### ISSUE TITLE
The config was manipulated. it can not be restored.

### ISSUE THREAD

**Issue by midozalouk** [r3d5ky/sercomm_cfg_unpacker#2]
Hello sir 
after using your code to unpack and repack the config file
it throws the following error `The config was manipulated. it can not be restored`.

is there any fix for that 

Here is the config file and the edited one 
[configurationBackup_changed.zip](https://github.com/r3d5ky/sercomm_cfg_unpacker/files/13404039/configurationBackup_changed.zip)

Any help will be apprciated

**Comment by midozalouk** [comment]
Here is a screenshot of the error

![Screenshot 2023-11-19 200636](https://github.com/r3d5ky/sercomm_cfg_unpacker/assets/2486418/82998aa4-0708-4f07-be4b-013da9fa2d35)

**Comment by r3d5ky** [comment]
> is there any fix for that

It looks like that you packed your config twice, or (more likely) you passed original config file instead of unpacked to the script, so check what files you are giving to the script. For unpacking you should run `python cfgtool.py -u config.cfg` and for packing `python cfgtool.py -p config.xml`

**Comment by midozalouk** [comment]
Thanks sir
You are absolutely right ❤️❤️❤️
I have another issue may be unrelated to your script

I have followed the guide and successfully installed openwrt but after reboot i lose openwrt and back to the original firmware

If you can help me please
Thanks

**Comment by midozalouk** [comment]
Solved

**Comment by r3d5ky** [comment]
> after reboot i lose openwrt and back to the original firmware

This is because of bootloader switching firmware slots, you can read about this in openwrt page for your device or similar (smartbox turbo for example).
